model:
  instantiation:
    model_path: "fasterrcnn_test/model.py"
    weight_path: "fasterrcnn_test/dior_clean_best.pt"
    model_name: "TorchvisionDetector"
    parameters:
      num_classes: 20
      network: "fasterrcnn"
      pretrained: true
      trainable_backbone_layers: 3
  estimator:
    framework: "pytorch"
    task: "detection"
    parameters:
      input_shape: [3, -1, -1]
      clip_values: [0, 1]
      device: "cuda"
      device_type: "gpu"
      batch_size: 1
      score_threshold: 0.0

evaluation:
  # basic: ["map", "accuracy", "precision"]
  robustness:
    corruption:
      default_metrics:
        - perturbation_magnitude
        - performance_drop_rate
        - perturbation_tolerance
      default_severities: [1, 3, 5]
      corruptions:
        gaussian_noise:
          method: "gaussian_noise"
          metrics:
            - performance_drop_rate
            - perturbation_tolerance
          severities: [1, 2, 3]
          parameters:
            magnitude: 0.05
        gaussian_blur:
          method: "gaussian_blur"
          severities: [1, 3, 5]
          parameters:
            kernel_multiplier: 2
        brightness_shift:
          method: "brightness_shift"
          metrics:
            - perturbation_magnitude
            - performance_drop_rate
          severities: [2, 4]
          parameters:
            max_shift: 0.25
        contrast_shift:
          method: "contrast_shift"
          metrics:
            - perturbation_magnitude
            - perturbation_tolerance
          severities: [1, 3, 5]
          parameters:
            max_shift: 0.4
  interpretability: []
  safety: []
  generalization: []
  fairness: []
